export const getCategoryData = () => {
  return {
    tags: [
      { id: 1, name: 'tag-example-here', label: 'Tag example here' },
      {
        id: 2,
        name: 'long-tag-title-here-long-tag-title-here',
        label: 'Long tag title here long tag title here',
      },
      { id: 3, name: 'short-tag', label: 'Short tag' },
      { id: 4, name: 'tag-example-here', label: 'Tag example here' },
      { id: 5, name: 'tag-example-here', label: 'Tag example here' },
      { id: 6, name: 'tag-example-here', label: 'Tag example here' },
      {
        id: 7,
        name: 'long-tag-title-here-long-tag-title-here',
        label: 'Long tag title here long tag title here',
      },
      { id: 8, name: 'tag-example-here', label: 'Tag example here' },
      { id: 9, name: 'tag-example-here', label: 'Tag example here' },
      {
        id: 10,
        name: 'long-tag-title-here-long-tag-title-here',
        label: 'Long tag title here long tag title here',
      },
      { id: 11, name: 'tag-example-here', label: 'Tag example here' },
      { id: 12, name: 'tag-example-here', label: 'Tag example here' },
      { id: 13, name: 'short-tag', label: 'Short tag' },
      { id: 14, name: 'tag-example-here', label: 'Tag example here' },
      { id: 15, name: 'tag-example-here', label: 'Tag example here' },
      { id: 16, name: 'tag-example-here', label: 'Tag example here' },
      {
        id: 17,
        name: 'long-tag-title-here-long-tag-title-here',
        label: 'Long tag title here long tag title here',
      },
      { id: 18, name: 'tag-example-here', label: 'Tag example here' },
      { id: 19, name: 'tag-example-here', label: 'Tag example here' },
      {
        id: 20,
        name: 'long-tag-title-here-long-tag-title-here',
        label: 'Long tag title here long tag title here',
      },
      { id: 21, name: 'tag-example-here', label: 'Tag example here' },
      { id: 22, name: 'tag-example-here', label: 'Tag example here' },
      { id: 23, name: 'short-tag', label: 'Short tag' },
      { id: 24, name: 'tag-example-here', label: 'Tag example here' },
      { id: 25, name: 'tag-example-here', label: 'Tag example here' },
      { id: 26, name: 'tag-example-here', label: 'Tag example here' },
      {
        id: 27,
        name: 'long-tag-title-here-long-tag-title-here',
        label: 'Long tag title here long tag title here',
      },
      { id: 28, name: 'tag-example-here', label: 'Tag example here' },
      { id: 29, name: 'tag-example-here', label: 'Tag example here' },
      {
        id: 30,
        name: 'long-tag-title-here-long-tag-title-here',
        label: 'Long tag title here long tag title here',
      },
      { id: 31, name: 'tag-example-here', label: 'Tag example here' },
      { id: 32, name: 'tag-example-here', label: 'Tag example here' },
      { id: 33, name: 'short-tag', label: 'Short tag' },
      { id: 34, name: 'tag-example-here', label: 'Tag example here' },
      { id: 35, name: 'tag-example-here', label: 'Tag example here' },
      { id: 36, name: 'tag-example-here', label: 'Tag example here' },
      {
        id: 37,
        name: 'long-tag-title-here-long-tag-title-here',
        label: 'Long tag title here long tag title here',
      },
      { id: 38, name: 'tag-example-here', label: 'Tag example here' },
      { id: 39, name: 'tag-example-here', label: 'Tag example here' },
      {
        id: 40,
        name: 'long-tag-title-here-long-tag-title-here',
        label: 'Long tag title here long tag title here',
      },
      { id: 41, name: 'tag-example-here', label: 'Tag example here' },
      { id: 42, name: 'tag-example-here', label: 'Tag example here' },
      { id: 33, name: 'short-tag', label: 'Short tag' },
      { id: 44, name: 'tag-example-here', label: 'Tag example here' },
      { id: 45, name: 'tag-example-here', label: 'Tag example here' },
      { id: 46, name: 'tag-example-here', label: 'Tag example here' },
      {
        id: 47,
        name: 'long-tag-title-here-long-tag-title-here',
        label: 'Long tag title here long tag title here',
      },
      { id: 48, name: 'tag-example-here', label: 'Tag example here' },
      { id: 49, name: 'tag-example-here', label: 'Tag example here' },
      {
        id: 50,
        name: 'long-tag-title-here-long-tag-title-here',
        label: 'Long tag title here long tag title here',
      },
      { id: 51, name: 'tag-example-here', label: 'Tag example here' },
      { id: 52, name: 'tag-example-here', label: 'Tag example here' },
    ],
  };
};
