export const dummyTags = {
  country: [
    { title: 'Tag1', to: '/tag1' },
    { title: 'Tag2', to: '/tag2' },
    { title: 'Tag3', to: '/tag3' },
    { title: 'Tag4', to: '/tag4' },
    { title: 'Tag5', to: '/tag5' },
  ],
  organisation: [
    { title: 'Tag1', to: '/tag1' },
    { title: 'Tag2', to: '/tag2' },
    { title: 'Tag3', to: '/tag3' },
    { title: 'Tag4', to: '/tag4' },
    { title: 'Tag5', to: '/tag5' },
    { title: 'Tag6', to: '/tag6' },
    { title: 'Tag7', to: '/tag7' },
    { title: 'Tag8', to: '/tag8' },
    { title: 'Tag9', to: '/tag9' },
    { title: 'Tag10', to: '/tag10' },
    { title: 'Tag11', to: '/tag11' },
  ],
  topic: [
    { title: 'Tag1', to: '/tag1' },
    { title: 'Tag2', to: '/tag2' },
    { title: 'Tag3', to: '/tag3' },
    { title: 'Tag4', to: '/tag4' },
    { title: 'Tag5', to: '/tag5' },
    { title: 'Tag6', to: '/tag6' },
    { title: 'Tag7', to: '/tag7' },
    { title: 'Tag8', to: '/tag8' },
    { title: 'Tag9', to: '/tag9' },
    { title: 'Tag10', to: '/tag10' },
    { title: 'Tag11', to: '/tag11' },
  ],
  area: [
    { title: 'Tag1', to: '/tag1' },
    { title: 'Tag2', to: '/tag2' },
    { title: 'Tag3', to: '/tag3' },
    { title: 'Tag4', to: '/tag4' },
    { title: 'Tag5', to: '/tag5' },
  ],
  people: [
    { title: 'Tag1', to: '/tag1' },
    { title: 'Tag2', to: '/tag2' },
    { title: 'Tag3', to: '/tag3' },
    { title: 'Tag4', to: '/tag4' },
    { title: 'Tag5', to: '/tag5' },
    { title: 'Tag6', to: '/tag6' },
    { title: 'Tag7', to: '/tag7' },
  ],
};
