import * as S from './style';
import {
  Typography as T,
  Grid,
  Image,
  Tags,
  MoreInformation,
  Button,
  TimelineGraphic,
} from '../../components';

import { dummyTags } from './dummy-data';
import SocialSection from './SocialSection';

const { Col, Row } = Grid;
const { ArticleTag, Category } = Tags;

const ArticlePage = () => {
  return (
    <>
      <T.H2>Haitian Revolution</T.H2>
      <ArticleTag
        shape="square"
        shapeColor="primaryMain"
        label="Date"
        value="10 January 1804"
        mt="30px"
      />
      <S.ArticleContent>
        <SocialSection url="https://github.com/" />

        <Image image="haitianRevolution2" mt="36px" mtT="2" />
        <T.P mt="5" mb="2">
          Contemporary depiction of the revolution
        </T.P>

        <Row mt="9">
          <Col w={[4, 10, 10]}>
            <T.P>
              On this day, 1 January 1804, Haiti became an independent republic,
              following the revolution which had begun 13 years earlier as a
              rebellion of enslaved people against slavery and French
              colonialism. Previously known as Saint-Domingue, it was the most
              profitable colony in the world, generating greater revenue than
              all of the continental North American colonies combined. This
              immense wealth was generated by the sweat and blood of enslaved
              Africans who were being worked to death in their tens of thousands
              on coffee and sugar plantations. Shortly after the French
              revolution, which supposedly espoused the ideals of "liberty,
              equality and fraternity," on August 22, 1791 a slave rebellion
              erupted, demanding those ideals be realised, and slavery and
              colonialism abolished.
            </T.P>
            <T.P mt="5">
              Over the coming years, the rebels successfully defeated the
              combined armies of the world's biggest colonial powers: France,
              Spain and Britain. The 1804 declaration of independence abolished
              the colony of Saint-Domingue and reinstated the Indigenous Taino
              name of Hayti. Europe and the US then promptly ostracised the
              fledgling republic, causing severe economic hardship. In 1825,
              France finally agreed to recognise Haiti's independence, provided
              it compensate former slaveowners to the tune of 150 million gold
              francs ($21 billion today) - a ransom which deeply impoverished
              the government and was not fully repaid until 1947. The United
              States only recognised Haitian independence in 1862, but this did
              not prevent it from invading and occupying it in 1915.
            </T.P>
          </Col>
        </Row>
      </S.ArticleContent>
      <S.MapSection mt="11" mb="3">
        <Image image="map" width="100%" />
      </S.MapSection>
      <MoreInformation
        mt="9"
        mb="2"
        subtitle="CLR James, A History of Pan African Revolt,"
        link="https://shop.workingclasshistory.com/products/a-history-of-pan-african-revolt-c-l-r-james"
      />
      <MoreInformation
        mt="9"
        mb="8"
        title="Sources"
        subtitle="“Haitian independence 1804-5,” Brown University, accessed July 8, 2019,"
        link="https://library.brown.edu/haitihistory/11.html"
      />
      <ArticleTag
        shape="triangle"
        shapeColor="primaryMain"
        label="Author"
        value="Working Class History"
        mt="5"
      />
      <ArticleTag
        shape="circle"
        shapeColor="primaryMain"
        label="Fact checker"
        value="Working Class History"
        mt="5"
      />
      <ArticleTag
        shape="Last edited"
        shapeColor="primaryMain"
        label="Date"
        value="15 August 2021"
        mt="5"
      />
      <T.H3 mt="9">Related tags</T.H3>
      <Row>
        <Col w={[4, 12, 6]} mt="6">
          <Category
            shape="square"
            shapeColor="primaryMain"
            size="small"
            title="People"
            to="/people"
            relatedTags={dummyTags.people}
          />
        </Col>
        <Col w={[4, 12, 6]} mt="6">
          <Category
            shape="square"
            shapeColor="primaryMain"
            size="small"
            title="City/Area"
            to="/area"
            relatedTags={dummyTags.area}
          />
        </Col>
        <Col w={[4, 12, 6]} mt="6">
          <Category
            shape="circle"
            shapeColor="tertiaryMain"
            size="small"
            title="Topic"
            to="/topic"
            relatedTags={dummyTags.topic}
          />
        </Col>
        <Col w={[4, 12, 6]} mt="6">
          <Category
            shape="circle"
            shapeColor="tertiaryMain"
            size="small"
            title="Country"
            to="/country"
            relatedTags={dummyTags.country}
          />
        </Col>
        <Col w={[4, 12, 6]} mt="6">
          <Category
            shape="triangle"
            size="small"
            shapeColor="neutral"
            title="Organisation"
            to="/organisations"
            relatedTags={dummyTags.organisation}
          />
        </Col>
      </Row>
      <Row mt="9">
        <Col w={[4, 7, 7]}>
          <Button
            bgColor="neutral"
            textColor="primaryMain"
            text="Support us"
            to="/support-us"
          />
        </Col>
      </Row>
      <TimelineGraphic type="short" number="1804" />
    </>
  );
};

export default ArticlePage;
